# Generated by Django 5.0.6 on 2024-07-26 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagblog',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='blog.blog'),
        ),
    ]
