# Generated by Django 5.0.6 on 2024-07-13 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palavra',
            name='dica',
        ),
        migrations.AddField(
            model_name='dica',
            name='palavra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forca.palavra'),
        ),
    ]
