# Generated by Django 5.0.6 on 2024-07-13 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forca', '0002_remove_palavra_dica_dica_palavra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dica',
            name='palavra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dicas', to='forca.palavra'),
        ),
    ]
