# Generated by Django 5.0.3 on 2024-07-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citacao',
            name='citacao',
            field=models.CharField(max_length=1800),
        ),
    ]
